# Generated by Django 4.2.2 on 2023-06-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0008_alter_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='usertype',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
