# Generated by Django 4.2.2 on 2023-06-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0011_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
    ]
