# Generated by Django 4.2.2 on 2023-06-28 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0014_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
