# Generated by Django 4.2.2 on 2023-06-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intern', '0016_appointment_date_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
